---
title: "Analysis of Course Titles in MSI Computing Programs"
author: "Bret Staudt Willet, Annie Wofford, Lara Perez-Felkner, & Chantra Nhien"
date: "2023-09-21"
output: html_document
---

```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(tidyverse)
library(anytime)
library(lubridate)

library(quanteda)
#library(spacyr)
#library(quanteda.textplots)
#library(tidytext)
#library(topicmodels)
library(wordcloud)
library(wordcloud2)
library(RColorBrewer)
```

---

# Setup

---

```{r, message=FALSE, echo=FALSE, eval=FALSE}
univ_df <- 
  read_csv("msi-university-list.csv") %>%
  select(instname, opeid, stabbr) %>%
  rename(ope_id = opeid,
         state_id = stabbr)
```

```{r, echo=FALSE, eval=FALSE}
glimpse(univ_df)
```

```{r, message=FALSE, echo=FALSE, eval=FALSE}
course_df <- read_csv("msi-computing-course-titles.csv")
```

```{r, echo=FALSE, eval=FALSE}
glimpse(course_df)
```

```{r, echo=FALSE, eval=FALSE}
msi_by_program <-
  univ_df %>%
  right_join(course_df, by = "instname") %>%
  rename(inst_name = instname,
         cip_id = cip_program) %>%
  separate_wider_delim(cols = program, names = c("program_area", "program_level"), delim = " - ")
```

```{r, echo=FALSE, eval=FALSE}
rm(course_df)
rm(univ_df)
glimpse(msi_by_program)
```

```{r, echo=FALSE, eval=FALSE}
n_instituions <- msi_by_program %>% distinct(inst_name) %>% nrow()
n_programs <- msi_by_program %>% distinct(inst_name, program_area, program_level) %>% nrow()
n_departments <- msi_by_program %>% distinct(inst_name, department) %>% nrow()
n_colleges <- msi_by_program %>% distinct(inst_name, college, school) %>% nrow()
```


---

# Analysis

---

## Analyze by Level

```{r}
msi_by_program %>% count(program_level, sort = TRUE) %>% head(20)
```

```{r}
msi_by_program %>% count(program_area, sort = TRUE) %>% head(20)
```

```{r, echo=FALSE, eval=FALSE}
#spacyr::spacy_install()
spacy_initialize(model = "en_core_web_sm")
```

```{r, echo=FALSE}
singularize <- function (x) {
  spacyr::spacy_parse(x, tag = TRUE) %>%
    mutate(token = ifelse(tag == "NNS",
                          lemma,
                          token)
           ) %>%
    group_by(doc_id) %>% 
    summarize(text = paste0(token, collapse = " ")) %>%
    quanteda::corpus()
}
```

```{r, echo=FALSE} 
my_extra_stopwords <-
  c("NA", "n/a", "just", "also", "can", "like", "etc", "lot", "many", "much", 
    "even", "sure", "concentration", "specialization", "department", "division",
    "study", "area", "college", "school"
  )

my_compound_words <- 
  c("computer science", "information science", "information sciences",
    "data science", "physical sciences",
    "natural sciences", "behavioral sciences", "mathematical sciences", 
    "public administration", "applied science", "liberal arts", "media arts",
    "information technology", "information systems", 
    "electrical engineering", "computer engineering", "computer system", 
    "computer security", "information security", "computer network",
    "networked system", "natural language processing", "artificial intelligence",
    "information assurance", "data analytics", "learning analytics", 
    "cyber technology", "big data", "machine learning", "network security"
  )
```

### Top Program Terms

```{r, echo=FALSE} 
dfm_program <-
  msi_by_program %>%
  pull(program_area) %>% 
  quanteda::corpus() %>%
  singularize() %>%
  quanteda::tokens(
    remove_separators = TRUE,
    remove_punct = TRUE,
    remove_symbols = TRUE,
    remove_numbers = TRUE,
    remove_url = TRUE) %>%
  quanteda::tokens_select(min_nchar=2L) %>% #Filter: at least 2 letters 
  quanteda::tokens_compound(phrase(my_compound_words)) %>%
  quanteda::dfm(tolower = TRUE) %>% 
  quanteda::dfm_remove(c(my_extra_stopwords,
                 quanteda::stopwords("english")))

top_terms_program <- 
  quanteda::topfeatures(dfm_program, n = 500, scheme = "count") %>%
  as.list() %>%
  as_tibble() %>%
  pivot_longer(cols = everything(), 
               names_to = "term", 
               values_to = "n") %>%
  mutate(p = round(100*n/n_programs, 2))
head(top_terms_program, 10)
#View(top_terms_program)
```

### Top Department Terms

```{r, echo=FALSE} 
dfm_dept <-
  msi_by_program %>%
  distinct(inst_name, college, school, .keep_all = TRUE) %>%
  pull(department) %>% 
  quanteda::corpus() %>%
  singularize() %>%
  quanteda::tokens(
    remove_separators = TRUE,
    remove_punct = TRUE,
    remove_symbols = TRUE,
    remove_numbers = TRUE,
    remove_url = TRUE) %>%
  quanteda::tokens_select(min_nchar=2L) %>% #Filter: at least 3 letters 
  quanteda::tokens_compound(phrase(my_compound_words)) %>%
  quanteda::dfm(tolower = TRUE) %>% 
  quanteda::dfm_remove(c(my_extra_stopwords,
                 quanteda::stopwords("english")))

top_terms_dept <- 
  quanteda::topfeatures(dfm_dept, n = 500, scheme = "count") %>%
  as.list() %>%
  as_tibble() %>%
  pivot_longer(cols = everything(), 
               names_to = "term", 
               values_to = "n") %>%
  mutate(p = round(100*n/n_departments, 2))
head(top_terms_dept, 10)
#View(top_terms_dept)
```

### Top College/School Terms

```{r, echo=FALSE} 
dfm_college <-
  msi_by_program %>%
  distinct(inst_name, department, .keep_all = TRUE) %>%
  unite("college_school", college:school, sep = " ") %>%
  pull(college_school) %>%
  quanteda::corpus() %>%
  singularize() %>%
  quanteda::tokens(
    remove_separators = TRUE,
    remove_punct = TRUE,
    remove_symbols = TRUE,
    remove_numbers = TRUE,
    remove_url = TRUE) %>%
  quanteda::tokens_select(min_nchar=2L) %>% #Filter: at least 3 letters 
  quanteda::tokens_compound(phrase(my_compound_words)) %>%
  quanteda::dfm(tolower = TRUE) %>% 
  quanteda::dfm_remove(c(my_extra_stopwords,
                 quanteda::stopwords("english")))

top_terms_college <- 
  quanteda::topfeatures(dfm_college, n = 500, scheme = "count") %>%
  as.list() %>%
  as_tibble() %>%
  pivot_longer(cols = everything(), 
               names_to = "term", 
               values_to = "n")  %>%
  mutate(p = round(100*n/n_colleges, 2))
head(top_terms_college, 10)
#View(top_terms_college)
```















```{r, warning=FALSE, echo=FALSE} 
set.seed(082523)  # for reproducibility 
wordcloud(words = dfm_table_terms_overall$term, 
          freq = dfm_table_terms_overall$count, 
          min.freq = 5,
          max.words = 100, 
          random.order = FALSE, 
          rot.per = 0.35,
          colors = brewer.pal(8, "Dark2"),
          scale = c(3, 0.25)
)
```

```{r, echo=FALSE, eval=FALSE} 
set.seed(082523)  # for reproducibility 
wordcloud2(data = dfm_table_terms_overall,
           size = 1.0, 
           color = "random-dark"
)
```

### Terms by Program Count 

```{r, echo=FALSE}
dfm_table_terms_by_doc <- 
  quanteda::topfeatures(dfm_terms, n = 500, scheme = "docfreq") %>%
  as.list() %>%
  as_tibble() %>%
  pivot_longer(cols = everything(), 
               names_to = "term", 
               values_to = "count")
head(dfm_table_terms_by_doc, 10)
```

```{r, warning=FALSE, echo=FALSE} 
set.seed(082523)  # for reproducibility 
wordcloud(words = dfm_table_terms_by_doc$term, 
          freq = dfm_table_terms_by_doc$count, 
          min.freq = 5,
          max.words = 100, 
          random.order = FALSE, 
          rot.per = 0.35,
          colors = brewer.pal(8, "Dark2"),
          scale = c(2, 0.25)
)
```

```{r, echo=FALSE, eval=FALSE} 
wordcloud2(data = dfm_table_terms_by_doc,
           size = 1.0, 
           color = "random-dark"
)
```

```{r, echo=FALSE, eval=FALSE}
tfidf_all <- 
  quanteda::dfm_tfidf(dfm_terms) %>%
  quanteda::convert(to = "data.frame")
colnames(tfidf_all)[1] = "course"
```







---

## Analyze Course Titles

```{r}
msi_by_course <-
  msi_by_program %>%
  mutate(course_titles = str_split(course_titles, "; ")) %>%
  unnest(course_titles)
```

```{r}
glimpse(msi_by_course)
```

```{r}
msi_by_course %>% count(course_titles, sort = TRUE) %>% head(20)
```

```{r, echo=FALSE}
course_terms <- 
  msi_by_course$course_titles %>% 
  tolower() %>%
  str_c(collapse = " ") %>%
  str_split(" ")
terms_table <- 
  table(course_terms, dnn = "term") %>% 
  as.data.frame() %>% 
  dplyr::rename(n = Freq) %>%
  arrange(desc(n))
head(terms_table, 10)
```

```{r, echo=FALSE} 
my_extra_stopwords <-
  c("NA", "just", "also", "can", "like", "etc", "lot", "many", "much", 
    "even", "sure"
  )

my_extra_keywords <-
  c("computer science", "information science", "data science", "physical science",
    "natural science", "behavioral science", "mathematical science", 
    "public administration", "applied science", "liberal arts", 
    "information technology", "information system", 
    "electrical engineering", "computer engineering", "computer system", 
    "computer security", "information security", "computer network",
    "networked system", "natural language processing", "artificial intelligence",
    "information assurance", "data analytics", "learning analytics", 
    "cyber technology", "big data", "machine learning", "network security"
)

corpus_terms <-
  msi_by_course %>%
  plyr::ddply(.(ope_id, level_id), 
        summarize, 
        course_titles = paste(course_titles, collapse=" ")) 

dfm_terms <-
  corpus_terms %>%
  select(course_titles) %>% 
  quanteda::corpus(text_field = 'course_titles') %>%
  quanteda::tokens(
    remove_separators = TRUE,
    remove_punct = TRUE,
    remove_symbols = TRUE,
    remove_numbers = TRUE,
    remove_url = TRUE) %>%
  # quanteda::tokens_wordstem(language = quanteda_options("language_stemmer")) %>%
  quanteda::tokens_select(min_nchar=3L) %>% #Filter: at least 3 letters 
  quanteda::dfm(tolower = TRUE) %>%
  quanteda::dfm_remove(c(my_extra_stopwords,
                 quanteda::stopwords("english")))
```

### Terms by Total Count

```{r, echo=FALSE} 
dfm_table_terms_overall <- 
  quanteda::topfeatures(dfm_terms, n = 500, scheme = "count") %>%
  as.list() %>%
  as_tibble() %>%
  pivot_longer(cols = everything(), 
               names_to = "term", 
               values_to = "count")
head(dfm_table_terms_overall, 10)
```

```{r, warning=FALSE, echo=FALSE} 
set.seed(082523)  # for reproducibility 
wordcloud(words = dfm_table_terms_overall$term, 
          freq = dfm_table_terms_overall$count, 
          min.freq = 5,
          max.words = 100, 
          random.order = FALSE, 
          rot.per = 0.35,
          colors = brewer.pal(8, "Dark2"),
          scale = c(3, 0.25)
)
```

```{r, echo=FALSE, eval=FALSE} 
set.seed(082523)  # for reproducibility 
wordcloud2(data = dfm_table_terms_overall,
           size = 1.0, 
           color = "random-dark"
)
```

### Terms by Program Count 

```{r, echo=FALSE}
dfm_table_terms_by_doc <- 
  quanteda::topfeatures(dfm_terms, n = 500, scheme = "docfreq") %>%
  as.list() %>%
  as_tibble() %>%
  pivot_longer(cols = everything(), 
               names_to = "term", 
               values_to = "count")
head(dfm_table_terms_by_doc, 10)
```

```{r, warning=FALSE, echo=FALSE} 
set.seed(082523)  # for reproducibility 
wordcloud(words = dfm_table_terms_by_doc$term, 
          freq = dfm_table_terms_by_doc$count, 
          min.freq = 5,
          max.words = 100, 
          random.order = FALSE, 
          rot.per = 0.35,
          colors = brewer.pal(8, "Dark2"),
          scale = c(2, 0.25)
)
```

```{r, echo=FALSE, eval=FALSE} 
wordcloud2(data = dfm_table_terms_by_doc,
           size = 1.0, 
           color = "random-dark"
)
```

```{r, echo=FALSE, eval=FALSE}
tfidf_all <- 
  quanteda::dfm_tfidf(dfm_terms) %>%
  quanteda::convert(to = "data.frame")
colnames(tfidf_all)[1] = "course"
```